# Generated by Django 2.2.19 on 2021-04-20 16:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiosk', '0033_auto_20210420_1145'),
        ('clinics', '0012_auto_20210420_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active')], default='active', max_length=100, no_check_for_status=True)),
                ('provider', models.CharField(blank=True, choices=[('Epic', 'Epic')], help_text='EHR Vendor for Clinic', max_length=15, verbose_name='Provider')),
                ('prod_key', fernet_fields.fields.EncryptedCharField(blank=True, help_text='API Key for Production', max_length=100, verbose_name='Production Key')),
                ('stage_key', fernet_fields.fields.EncryptedCharField(blank=True, help_text='API Key for Test', max_length=100, verbose_name='Staging Key')),
                ('version', models.CharField(blank=True, max_length=125, verbose_name='Version')),
                ('fhir_version', models.CharField(blank=True, choices=[('DSTU2', 'DSTU2'), ('STU3', 'STU3'), ('R4', 'R4')], help_text='EHR FHIR version', max_length=15, verbose_name='FHIR Version')),
                ('iss_url', models.CharField(blank=True, max_length=255, verbose_name='Root URL')),
                ('authorize_url', models.CharField(blank=True, max_length=255, verbose_name='Authorization URL')),
                ('token_url', models.CharField(blank=True, max_length=255, verbose_name='Token URL')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Metadata retrieved from the ISS endpoint during Smart on FHIR OAUTH.', null=True, verbose_name='FHIR Metadata')),
            ],
            options={
                'verbose_name': 'Epic Settings',
                'verbose_name_plural': 'Epic Settings',
            },
        ),
        migrations.CreateModel(
            name='PatientEhrIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active')], default='active', max_length=100, no_check_for_status=True)),
                ('fhir_id', models.CharField(blank=True, max_length=64, verbose_name='FHIR ID')),
                ('epic_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.EpicSettings')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpicDepartmentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active')], default='active', max_length=100, no_check_for_status=True)),
                ('location_code', models.CharField(blank=True, help_text='Key used to determine the location during oauth', max_length=20, null=True, unique=True, verbose_name='Location Code')),
                ('narrative_note_key', models.CharField(blank=True, max_length=100, verbose_name='Narrative Note Type Code')),
                ('stability_plan_note_key', models.CharField(blank=True, max_length=100, verbose_name='Stability Plan Type Code')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.Department', verbose_name='Department')),
                ('epic_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.EpicSettings')),
            ],
            options={
                'verbose_name': 'Epic Department Settings',
                'verbose_name_plural': 'Epic Department Settings',
            },
        ),
    ]
