# Generated by Django 2.2.19 on 2021-05-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_auto_20210506_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicdepartmentsettings',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.Department', verbose_name='Department'),
        ),
    ]
