# Generated by Django 2.2.24 on 2021-06-10 21:32

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0003_auto_20210507_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epicsettings',
            name='prod_key',
        ),
        migrations.RemoveField(
            model_name='epicsettings',
            name='stage_key',
        ),
        migrations.RemoveField(
            model_name='epicsettings',
            name='version',
        ),
        migrations.AddField(
            model_name='epicsettings',
            name='private_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Private Key', max_length=2048, verbose_name='Private Key'),
        ),
        migrations.AddField(
            model_name='epicsettings',
            name='public_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Public Key.  This is stored here for easy access/reference but is not used in the API', max_length=2048, verbose_name='Public Key'),
        ),
    ]
