# Generated by Django 2.2.24 on 2021-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0005_auto_20210729_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicdepartmentsettings',
            name='location_code',
            field=models.CharField(blank=True, help_text='Key used to determine the location during oauth',
                                   max_length=64, null=True, verbose_name='Location Code'),
        ),
        migrations.AlterUniqueTogether(
            name='epicdepartmentsettings',
            unique_together={('epic_settings', 'location_code')},
        ),

    ]
