# Generated by Django 2.2.24 on 2021-08-23 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0058_assessmentlocks_acknowledged'),
        ('epic', '0006_auto_20210809_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('trigger', models.CharField(blank=True, help_text='What triggered the note to be sent to an EMR?', max_length=120, verbose_name='Trigger')),
                ('note', fernet_fields.fields.EncryptedTextField(blank=True, help_text='Text of the note sent to the EMR', verbose_name='Note')),
                ('note_type', models.CharField(choices=[('narrative_note', 'Narrative Note'), ('stability_plan', 'Stability Plan')], max_length=15, verbose_name='Note Type')),
                ('fhir_id', models.CharField(blank=True, help_text='ID of the note saved in the EMR', max_length=256, null=True, verbose_name='FHIR ID')),
                ('sent_to_ehr', models.BooleanField(default=False, help_text='Indicates if the note was sent to an EMR or only copied locally', verbose_name='Sent to EHR')),
                ('patient_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.PatientSession')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Technician')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
