# Generated by Django 2.2.24 on 2021-09-07 18:14

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0007_noteslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicsettings',
            name='private_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Private Key', max_length=2048, verbose_name='Private Key'),
        ),
        migrations.AlterField(
            model_name='epicsettings',
            name='public_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Public Key.  This is stored here for easy access/reference but is not used in the API', max_length=2048, verbose_name='Public Key'),
        ),
    ]
