# Generated by Django 2.2.24 on 2021-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0008_auto_20210907_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicdepartmentsettings',
            name='location_code',
            field=models.CharField(blank=True, help_text='Key used to determine the location during oauth.This must match the ENCDEPID stored in Epic for the department', max_length=64, null=True, verbose_name='Location Code'),
        ),
    ]
