# Generated by Django 2.2.24 on 2021-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0009_auto_20210908_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicdepartmentsettings',
            name='narrative_note_system_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Narrative Note System Code'),
        ),
        migrations.AddField(
            model_name='epicdepartmentsettings',
            name='stability_plan_system_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Narrative Note System Code'),
        ),
    ]
