# Generated by Django 2.2.24 on 2021-10-13 17:14

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0011_auto_20210909_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicsettings',
            name='private_key_pem',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Private Key'),
        ),
    ]
