# Generated by Django 2.2.24 on 2021-10-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0012_epicsettings_private_key_pem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteslog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.Technician'),
        ),
    ]
