# Generated by Django 2.2.24 on 2021-11-30 23:51

from django.db import migrations, models

def populate_encounter(apps, schema_editor):
    NotesLog = apps.get_model("epic", "NotesLog")
    for record in NotesLog.objects.all():
        record.encounter = record.patient_session.encounter
        record.save()



class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0063_auto_20211011_1636'),
        ('epic', '0013_auto_20211008_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteslog',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='kiosk.Encounter'),
        ),
        migrations.RunPython(
            populate_encounter
        ),
        migrations.AlterField(
            model_name='noteslog',
            name='encounter',
            field=models.ForeignKey(on_delete=models.CASCADE, to='kiosk.Encounter'),
        ),
        migrations.RemoveField(
            model_name='noteslog',
            name='patient_session',
        ),
    ]
