# Generated by Django 3.2.12 on 2022-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0014_noteslog_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteslog',
            name='trigger',
            field=models.CharField(blank=True, help_text='What triggered the note to be sent to an EMR?', max_length=120, null=True, verbose_name='Trigger'),
        ),
    ]
