# Generated by Django 3.2.12 on 2022-04-19 20:51

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0015_alter_noteslog_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteslog',
            name='response',
            field=models.TextField(blank=True, help_text='Response from EHR Server after saving', null=True),
        ),
        migrations.AddField(
            model_name='noteslog',
            name='status',
            field=model_utils.fields.StatusField(choices=[('not-sent', 'Not Sent'), ('in-progress', 'In Progress'), ('failed', 'Failed'), ('sent', 'Sent')], default='not-sent', max_length=100, no_check_for_status=True),
        ),
    ]