repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - { id: trailing-whitespace, args: ["--markdown-linebreak-ext=md"] }
      - { id: check-ast }
      - { id: debug-statements }

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - {
          id: isort,
          types: [ "python" ]
        }

  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - { id: black, language_version: python3.10 }
