[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py310']


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88


[tool.coverage.run]
include = ["jaspr/*"]
omit = [
  "*migrations*",
  "*tests*",
  "jaspr/apps/bootstrap/fixtureize/*",
  "jaspr/apps/bootstrap/management/commands/dump_fixtures.py",
  "jaspr/apps/bootstrap/management/commands/load_fixtures.py",
  "jaspr/apps/ssi/management/commands/import_questions_json_style_file.py",
]


[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = 120
