# Generated by Django 2.2.13 on 2020-07-31 22:12

from django.db import migrations
from jaspr.apps.accounts.models import User as NonMigrationUserModel


def set_current_security_chars(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    to_update = []
    batch_size = 50
    for user in User.objects.all().iterator():
        user.SECURITY_CHARS_MAX_LENGTH = NonMigrationUserModel.SECURITY_CHARS_MAX_LENGTH
        NonMigrationUserModel.generate_and_set_current_security_chars(user)
        to_update.append(user)
        if len(to_update) == batch_size:
            User.objects.bulk_update(
                to_update, ["current_security_chars"], batch_size=batch_size
            )
            to_update.clear()
    if to_update:
        User.objects.bulk_update(
            to_update, ["current_security_chars"], batch_size=batch_size
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_current_security_chars"),
    ]

    operations = [migrations.RunPython(set_current_security_chars, elidable=True)]
