# Generated by Django 2.2.20 on 2021-05-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalsecurityquestion_securityquestion'),
        ('kiosk', '0039_auto_20210610_1640')
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalSecurityQuestion',
        ),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
