# Generated by Django 3.2.12 on 2022-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210513_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedoutauthtoken',
            name='salt',
        ),
    ]
