# Generated by Django 2.2.13 on 2020-10-26 19:37

from django.db import migrations, models

import jaspr.apps.awsmedia.fields


class Migration(migrations.Migration):

    dependencies = [
        ("awsmedia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedia",
            name="file_field_original_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original name of file_field before hashing.",
                max_length=510,
                verbose_name="Original Name of File",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="file_field_original_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original name of file_field before hashing.",
                max_length=510,
                verbose_name="Original Name of File",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file_field",
            field=jaspr.apps.awsmedia.fields.PrimaryFileField(
                max_length=510, upload_to="", verbose_name="File Field"
            ),
        ),
    ]
