# Generated by Django 2.2.13 on 2020-10-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awsmedia", "0003_custom_update_file_field_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmedia",
            name="file_field_original_name",
            field=models.CharField(
                help_text="Original name of file_field before hashing.",
                max_length=510,
                verbose_name="Original Name of File",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file_field_original_name",
            field=models.CharField(
                help_text="Original name of file_field before hashing.",
                max_length=510,
                verbose_name="Original Name of File",
            ),
        ),
    ]
