# Generated by Django 2.2.13 on 2020-06-19 21:32

import django.db.models.deletion
import django.utils.timezone
import jaspr.apps.common.fields.encrypted_json_field
import jaspr.apps.stability_plan.models
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kiosk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientWalkthrough",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kiosk.Patient"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Walkthrough",
                "verbose_name_plural": "Patient Walkthroughs",
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("draft", "draft")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Administrative shorthand name.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Administrative notes about this step. Not publicly viewable.",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Default Object ID",
                    ),
                ),
                (
                    "frontend_render_type",
                    models.CharField(
                        choices=[
                            ("activity", "activity"),
                            ("breathe", "breathe"),
                            ("copingStrategy", "copingStrategy"),
                            ("guide", "guide"),
                            ("lethalMeans", "lethalMeans"),
                            ("nationalHotline", "nationalHotline"),
                            ("personalizedLethalMeans", "personalizedLethalMeans"),
                            ("reasonsForLiving", "reasonsForLiving"),
                            ("recap", "recap"),
                            ("sharedStory", "sharedStory"),
                            ("supportivePeople", "supportivePeople"),
                            ("video", "video"),
                            ("videoDescription", "videoDescription"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "skip_if_blank",
                    models.BooleanField(default=False, verbose_name="Skip If Blank"),
                ),
                ("function", models.CharField(blank=True, max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=jaspr.apps.stability_plan.models.get_walkthrough_content_types_filter,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_set",
                        to="contenttypes.ContentType",
                        verbose_name="Default Content Type",
                    ),
                ),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Walkthrough",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("draft", "draft"),
                        ],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="WalkthroughStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("draft", "draft")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stability_plan.Step",
                    ),
                ),
                (
                    "walkthrough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stability_plan.Walkthrough",
                    ),
                ),
            ],
            options={
                "verbose_name": "Walkthrough Step",
                "verbose_name_plural": "Walkthrough Steps",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="PatientWalkthroughStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "value",
                    jaspr.apps.common.fields.encrypted_json_field.EncryptedJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "frontend_render_type",
                    models.CharField(
                        choices=[
                            ("activity", "activity"),
                            ("breathe", "breathe"),
                            ("copingStrategy", "copingStrategy"),
                            ("guide", "guide"),
                            ("lethalMeans", "lethalMeans"),
                            ("nationalHotline", "nationalHotline"),
                            ("personalizedLethalMeans", "personalizedLethalMeans"),
                            ("reasonsForLiving", "reasonsForLiving"),
                            ("recap", "recap"),
                            ("sharedStory", "sharedStory"),
                            ("supportivePeople", "supportivePeople"),
                            ("video", "video"),
                            ("videoDescription", "videoDescription"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "patient_walkthrough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stability_plan.PatientWalkthrough",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stability_plan.Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Walkthrough Step",
                "verbose_name_plural": "Patient Walkthrough Steps",
            },
        ),
        migrations.AddField(
            model_name="patientwalkthrough",
            name="walkthrough",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stability_plan.Walkthrough",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWalkthroughStep",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("choice1", "choice1"), ("choice2", "choice2")],
                        default="choice1",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stability_plan.Step",
                    ),
                ),
                (
                    "walkthrough",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stability_plan.Walkthrough",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Walkthrough Step",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWalkthrough",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("choice1", "choice1"), ("choice2", "choice2")],
                        default="choice1",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical walkthrough",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStep",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("choice1", "choice1"), ("choice2", "choice2")],
                        default="choice1",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Administrative shorthand name.",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Administrative notes about this step. Not publicly viewable.",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Default Object ID",
                    ),
                ),
                (
                    "frontend_render_type",
                    models.CharField(
                        choices=[
                            ("activity", "activity"),
                            ("breathe", "breathe"),
                            ("copingStrategy", "copingStrategy"),
                            ("guide", "guide"),
                            ("lethalMeans", "lethalMeans"),
                            ("nationalHotline", "nationalHotline"),
                            ("personalizedLethalMeans", "personalizedLethalMeans"),
                            ("reasonsForLiving", "reasonsForLiving"),
                            ("recap", "recap"),
                            ("sharedStory", "sharedStory"),
                            ("supportivePeople", "supportivePeople"),
                            ("video", "video"),
                            ("videoDescription", "videoDescription"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "skip_if_blank",
                    models.BooleanField(default=False, verbose_name="Skip If Blank"),
                ),
                ("function", models.CharField(blank=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to=jaspr.apps.stability_plan.models.get_walkthrough_content_types_filter,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.ContentType",
                        verbose_name="Default Content Type",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical step",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPatientWalkthroughStep",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("choice1", "choice1"), ("choice2", "choice2")],
                        default="choice1",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "value",
                    jaspr.apps.common.fields.encrypted_json_field.EncryptedJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "frontend_render_type",
                    models.CharField(
                        choices=[
                            ("activity", "activity"),
                            ("breathe", "breathe"),
                            ("copingStrategy", "copingStrategy"),
                            ("guide", "guide"),
                            ("lethalMeans", "lethalMeans"),
                            ("nationalHotline", "nationalHotline"),
                            ("personalizedLethalMeans", "personalizedLethalMeans"),
                            ("reasonsForLiving", "reasonsForLiving"),
                            ("recap", "recap"),
                            ("sharedStory", "sharedStory"),
                            ("supportivePeople", "supportivePeople"),
                            ("video", "video"),
                            ("videoDescription", "videoDescription"),
                        ],
                        max_length=25,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient_walkthrough",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stability_plan.PatientWalkthrough",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stability_plan.Step",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Patient Walkthrough Step",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPatientWalkthrough",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("choice1", "choice1"), ("choice2", "choice2")],
                        default="choice1",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="kiosk.Patient",
                    ),
                ),
                (
                    "walkthrough",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="stability_plan.Walkthrough",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Patient Walkthrough",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="walkthroughstep",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active"),
                fields=("walkthrough", "order"),
                name="unique_walkthrough_step_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="walkthroughstep",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active"),
                fields=("walkthrough", "step"),
                name="unique_walkthrough_with_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientwalkthrough",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active"),
                fields=("patient",),
                name="unique_active_patient",
            ),
        ),
    ]
