# Generated by Django 2.2.13 on 2020-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stability_plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientwalkthroughstep",
            options={
                "ordering": ("order",),
                "verbose_name": "Patient Walkthrough Step",
                "verbose_name_plural": "Patient Walkthrough Steps",
            },
        ),
        migrations.AddField(
            model_name="historicalpatientwalkthroughstep",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Copied from Walkthrough Step"
            ),
        ),
        migrations.AddField(
            model_name="patientwalkthroughstep",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Copied from Walkthrough Step"
            ),
        ),
    ]
