# Generated by Django 2.2.13 on 2020-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stability_plan", "0002_auto_20200702_1213"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patientwalkthroughstep",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active"),
                fields=("patient_walkthrough", "step", "order"),
                name="unique_active_patientwalkthroughsteporder",
            ),
        ),
    ]
