# Generated by Django 3.0.14 on 2022-02-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stability_plan', '0003_auto_20200702_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientwalkthroughstep',
            options={'ordering': ['order'], 'verbose_name': 'Patient Walkthrough Step', 'verbose_name_plural': 'Patient Walkthrough Steps'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='walkthrough',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='walkthroughstep',
            options={'ordering': ['order'], 'verbose_name': 'Walkthrough Step', 'verbose_name_plural': 'Walkthrough Steps'},
        ),
    ]
