# Generated by Django 2.2.13 on 2020-07-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0003_auto_20200626_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action",
            field=models.CharField(
                choices=[
                    ("Arrive", "Time of arriving @ CAMS section"),
                    ("CarePlanningReportClosed", "Time user closes Planning Report."),
                    ("CarePlanningReportOpen", "Time user opens Planning Report."),
                    (
                        "Explore",
                        "Time of selecting Explore on my own button after tutorial",
                    ),
                    (
                        "Guide",
                        "Time of selecting Continue Guidance button after tutorial",
                    ),
                    ("GuideJasper", "Time of selecting Jasper as the guide."),
                    ("GuideJaz", "Time of selecting Jaz as the guide."),
                    (
                        "HamburgerCAMS",
                        "Time of selecting CAMS button on hamburger menu",
                    ),
                    (
                        "HamburgerCS",
                        "Time of selecting comfort and skills button on hamburger menu",
                    ),
                    (
                        "HamburgerHome",
                        "Time of selecting Home button on hamburger menu",
                    ),
                    (
                        "HamburgerMyAccount",
                        "Time of selecting My Account button on hamburger menu",
                    ),
                    (
                        "HamburgerSS",
                        "Time of selecting Shared Stories button on hamburger menu",
                    ),
                    (
                        "HamburgerTK",
                        "Time of selecting Takeaway Kit button on hamburger menu",
                    ),
                    (
                        "HamburgerStabilityPlan",
                        "Time of selecting Stability Plan button on hamburger menu",
                    ),
                    (
                        "HamburgerContacts",
                        "Time of selecting Contacts button on hamburger menu",
                    ),
                    (
                        "HamburgerWalkthrough",
                        "Time of selecting the Distress Survival Guide button on hamburger menu",
                    ),
                    ("InterviewSummaryClosed", "Time user closes Interview Summary."),
                    ("InterviewSummaryOpen", "Time user opens Interview Summary."),
                    ("Lockout", "Time of lockout (10 min inactivity)"),
                    ("LogOutByUser", "Time of logout initiated by user"),
                    ("LogOutTimeout", "Time of logout (60 min inactivity)"),
                    ("MenuCAMS", "Time of selecting CAMS button on side menu"),
                    (
                        "MenuCS",
                        "Time of selecting comfort and skills button on side menu",
                    ),
                    ("MenuHome", "Time of selecting Home button on side menu"),
                    ("MenuSS", "Time of selecting Shared Stories button on side menu"),
                    ("MenuTK", "Time of selecting Takeaway Kit button on side menu"),
                    ("SessionStart", "Time of log in initiated by technician"),
                    ("SkipWTE", "Time of pressing 'Skip' before WTE video"),
                    ("Submit", "Time of submitting CAMS section"),
                    ("StabilityPlanClosed", "Time user closes Stability Plan."),
                    ("StabilityPlanOpen", "Time user opens Stability Plan."),
                    ("SummariesClosed", "Time user closes Summaries drawer."),
                    ("SummariesOpen", "Time user opens Summaries drawer."),
                    (
                        "Watch",
                        "Time user finishes (~95% progress at the time of writing) watching a video.",
                    ),
                    (
                        "JAHWalkthroughStart",
                        "Time user clicks to start the Walkthrough.",
                    ),
                    (
                        "JAHWalkthroughArrive",
                        "Time user arrives at specific content in the Walkthrough.",
                    ),
                    (
                        "JAHWalkthroughClickedMoreInfo",
                        "Time user clicks more info on a page of the Walkthrough.",
                    ),
                    (
                        "JAHWalkthroughArriveRecap",
                        "Time user gets to the list of their steps at the end of the Walkthrough and can choose to go back.",
                    ),
                    ("JAHWalkthroughEnd", "Time user leaves the Walkthrough."),
                    (
                        "JAHArriveContacts",
                        "Time user goes to their supportive people page.",
                    ),
                    (
                        "JAHArrivePeople",
                        "Time user clicks into page with their supportive people contacts.",
                    ),
                    (
                        "JAHArriveSupportivePerson",
                        "Time user clicks into a specific supportive person from either the home page or the contacts page.",
                    ),
                    (
                        "JAHArriveCrisisLine",
                        "Time user goes to specific crisis line page.",
                    ),
                    (
                        "JAHArrivePeopleMore",
                        'Time user clicks into "more about supportive people".',
                    ),
                    (
                        "JAHArriveConvoStarters",
                        'Time user clicks into "Conversation Starters".',
                    ),
                    (
                        "JAHUserCopy",
                        "Time user copies a starter, with the order number of the starter they copied specified.",
                    ),
                    (
                        "JAHArriveCommonConcerns",
                        'Time user clicks into "Common Concerns".',
                    ),
                    (
                        "JAHOpenConcern",
                        "Time user opens up a common concern, with the order number of the concern they opened specified.",
                    ),
                    (
                        "JAHArriveSSSupportivePeople",
                        "Time user clicks into Shared Stories: Supportive People.",
                    ),
                    (
                        "JAHArriveSSHotlines",
                        "Time user clicks into Shared Stories: Hotlines.",
                    ),
                    (
                        "JAHCallHotline",
                        "Time user clicks button to call the hotline (accessible from multiple screens).",
                    ),
                    (
                        "JAHTextHotline",
                        "Time user clicks button to text hotline (accessible from multiple screens).",
                    ),
                    (
                        "JAHCallSupportivePerson",
                        "Time user clicks button to call a supportive person (accessible from multiple screens).",
                    ),
                    (
                        "JAHTextSupportivePerson",
                        "Time user clicks button to text a supportive person (accessible from multiple screens).",
                    ),
                ],
                max_length=63,
                verbose_name="Action",
            ),
        ),
    ]
