# Generated by Django 2.2.13 on 2020-08-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0005_auto_20200731_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="activaterecord",
            name="new",
            field=models.BooleanField(
                default=False,
                help_text="Was this from activating a new Patient? Otherwise it'd be from activating an existing Patient.",
                verbose_name="New?",
            ),
            preserve_default=False,
        ),
    ]
