# Generated by Django 2.2.13 on 2020-08-04 00:02

from django.db import migrations
from django.db.models import OuterRef, PositiveIntegerField, Subquery


def set_activate_record_new(apps, schema_editor):
    Patient = apps.get_model("kiosk", "Patient")
    ActivateRecord = apps.get_model("kiosk", "ActivateRecord")

    activate_record_subquery = (
        ActivateRecord.objects.filter(patient_id=OuterRef("pk"))
        .order_by("timestamp")
        .values("pk")[:1]
    )
    patient_queryset = Patient.objects.all().annotate(
        first_activate_record=Subquery(
            activate_record_subquery, output_field=PositiveIntegerField(null=True)
        )
    )
    activate_record_pks = []
    for patient in patient_queryset:
        if patient.first_activate_record is not None:
            activate_record_pks.append(patient.first_activate_record)
    # NOTE: At the time of writing this data migration, we very likely don't have more
    # than 100 `Patient`s in any system, so it doesn't need to be super optimized.
    ActivateRecord.objects.filter(pk__in=activate_record_pks).update(new=True)


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0006_activaterecord_new"),
    ]

    operations = [migrations.RunPython(set_activate_record_new, elidable=True)]
