# Generated by Django 2.2.13 on 2020-08-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0007_manual_activate_record_new_initialization"),
    ]

    operations = [
        migrations.RemoveField(model_name="activaterecord", name="modified",),
    ]
