# Generated by Django 2.2.13 on 2020-08-04 15:12

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0008_remove_activaterecord_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltechnician",
            name="last_activated_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="The time the Technician was last activated at.",
                null=True,
                verbose_name="Last Activated At",
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="last_activated_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="The time the Technician was last activated at.",
                null=True,
                verbose_name="Last Activated At",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltechnician",
            name="activated_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                editable=False,
                help_text="The time the Technician was first activated at.",
                monitor="activated",
                null=True,
                verbose_name="First Activated At",
                when={True},
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="activated_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                editable=False,
                help_text="The time the Technician was first activated at.",
                monitor="activated",
                null=True,
                verbose_name="First Activated At",
                when={True},
            ),
        ),
    ]
