# Generated by Django 2.2.13 on 2020-08-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0009_auto_20200804_0812"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltechnician",
            old_name="activated_at",
            new_name="first_activated_at",
        ),
        migrations.RenameField(
            model_name="technician",
            old_name="activated_at",
            new_name="first_activated_at",
        ),
    ]
