# Generated by Django 2.2.13 on 2020-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0015_auto_20200812_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatient",
            name="analytics_token",
            field=models.UUIDField(
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AddField(
            model_name="historicaltechnician",
            name="analytics_token",
            field=models.UUIDField(
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="analytics_token",
            field=models.UUIDField(
                default=None,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="analytics_token",
            field=models.UUIDField(
                default=None,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Analytics Token",
            ),
        ),
    ]
