# Generated by Django 2.2.13 on 2020-09-04 18:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0017_manual_set_patient_and_technician_analytics_token_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatient",
            name="analytics_token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltechnician",
            name="analytics_token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="analytics_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="analytics_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Analytics Token",
            ),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
