# Generated by Django 2.2.13 on 2020-09-15 20:10

import django.core.validators
import fernet_fields.fields
import jaspr.apps.common.fields.encrypted_positive_small_integer_field
import jaspr.apps.common.fields.encrypted_small_integer_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0018_auto_20200904_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="scoring_current_attempt",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("Current Attempt", "Current Attempt"),
                    ("No Current Attempt", "No Current Attempt"),
                ],
                default=None,
                editable=False,
                max_length=31,
                null=True,
                verbose_name="Scoring - Current Attempt",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scoring_risk",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[("Low", "Low"), ("Moderate", "Moderate"), ("High", "High")],
                default=None,
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Scoring - Risk",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scoring_score",
            field=jaspr.apps.common.fields.encrypted_positive_small_integer_field.EncryptedPositiveSmallIntegerField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Scoring - Score",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scoring_suicide_index_score",
            field=jaspr.apps.common.fields.encrypted_small_integer_field.EncryptedSmallIntegerField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-2),
                    django.core.validators.MaxValueValidator(2),
                ],
                verbose_name="Scoring - Suicide Index Score",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scoring_suicide_index_score_typology",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("Wish to Live", "Wish to Live"),
                    ("Ambivalent", "Ambivalent"),
                    ("Wish to Die", "Wish to Die"),
                ],
                default=None,
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Scoring - Suicide Index Score Typology",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scoring_suicide_plan_and_intent",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("Suicide Plan and Intent", "Suicide Plan and Intent"),
                    ("Suicide Plan or Intent", "Suicide Plan or Intent"),
                    ("No Suicide Plan or Intent", "No Suicide Plan or Intent"),
                ],
                default=None,
                editable=False,
                max_length=31,
                null=True,
                verbose_name="Scoring - Suicide Plan and Intent",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="scoring_current_attempt",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("Current Attempt", "Current Attempt"),
                    ("No Current Attempt", "No Current Attempt"),
                ],
                default=None,
                editable=False,
                max_length=31,
                null=True,
                verbose_name="Scoring - Current Attempt",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="scoring_risk",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[("Low", "Low"), ("Moderate", "Moderate"), ("High", "High")],
                default=None,
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Scoring - Risk",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="scoring_score",
            field=jaspr.apps.common.fields.encrypted_positive_small_integer_field.EncryptedPositiveSmallIntegerField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Scoring - Score",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="scoring_suicide_index_score",
            field=jaspr.apps.common.fields.encrypted_small_integer_field.EncryptedSmallIntegerField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-2),
                    django.core.validators.MaxValueValidator(2),
                ],
                verbose_name="Scoring - Suicide Index Score",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="scoring_suicide_index_score_typology",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("Wish to Live", "Wish to Live"),
                    ("Ambivalent", "Ambivalent"),
                    ("Wish to Die", "Wish to Die"),
                ],
                default=None,
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Scoring - Suicide Index Score Typology",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="scoring_suicide_plan_and_intent",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("Suicide Plan and Intent", "Suicide Plan and Intent"),
                    ("Suicide Plan or Intent", "Suicide Plan or Intent"),
                    ("No Suicide Plan or Intent", "No Suicide Plan or Intent"),
                ],
                default=None,
                editable=False,
                max_length=31,
                null=True,
                verbose_name="Scoring - Suicide Plan and Intent",
            ),
        ),
    ]
