# Generated by Django 2.2.13 on 2020-10-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0020_amendment_historicalamendment"),
        ("kiosk", "0019_auto_20200924_1639"),
    ]

    operations = []
