# Generated by Django 2.2.13 on 2020-10-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0022_manual_populate_rate_psych_section_viewed"),
        ("kiosk", "0021_merge_20201005_1535"),
    ]

    operations = []
