# Generated by Django 2.2.13 on 2020-10-07 00:58

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0023_merge_20201005_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="times_tried",
            field=fernet_fields.fields.EncryptedCharField(
                choices=[
                    ("no attempts", "No Attempts"),
                    ("once", "Single Attempt"),
                    ("many", "Multiple Attempts (2 or more)"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="times_tried",
            field=fernet_fields.fields.EncryptedCharField(
                choices=[
                    ("no attempts", "No Attempts"),
                    ("once", "Single Attempt"),
                    ("many", "Multiple Attempts (2 or more)"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
