# Generated by Django 2.2.13 on 2020-12-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0024_auto_20201006_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="questionnaire_major_revision",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                help_text="The Major Revision for the Questionnaire. Currently, this can only be generated by the code, and is set to whatever the latest Major Revision of the Questionnaire is at the time this Assessment is created.",
                null=True,
                verbose_name="Questionnaire Major Revision",
            ),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="questionnaire_major_revision",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                help_text="The Major Revision for the Questionnaire. Currently, this can only be generated by the code, and is set to whatever the latest Major Revision of the Questionnaire is at the time this Assessment is created.",
                null=True,
                verbose_name="Questionnaire Major Revision",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiosk.Patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="kiosk.Patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="beta",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this Patient has permission to view test Questionnaire Versions marked with Beta = True.",
                verbose_name="Can See Beta Questionnaire Versions?",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="beta",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this Patient has permission to view test Questionnaire Versions marked with Beta = True.",
                verbose_name="Can See Beta Questionnaire Versions?",
            ),
        ),
    ]
