# Generated by Django 2.2.13 on 2020-12-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0025_auto_20201216_1314"),
        ("kiosk", "0026_manual_update_progress_indicator"),
    ]

    operations = []
