# Generated by Django 2.2.13 on 2021-02-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0028_auto_20210202_1426'),
        ('kiosk', '0028_auto_20210120_1631'),
    ]

    operations = [
    ]
