# Generated by Django 2.2.13 on 2021-02-21 21:18

import django.core.validators
from django.db import migrations
import jaspr.apps.common.fields.encrypted_positive_small_integer_field


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0029_merge_20210211_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='wish_die',
            field=jaspr.apps.common.fields.encrypted_positive_small_integer_field.EncryptedPositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='wish_live',
            field=jaspr.apps.common.fields.encrypted_positive_small_integer_field.EncryptedPositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='historicalassessment',
            name='wish_die',
            field=jaspr.apps.common.fields.encrypted_positive_small_integer_field.EncryptedPositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='historicalassessment',
            name='wish_live',
            field=jaspr.apps.common.fields.encrypted_positive_small_integer_field.EncryptedPositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
