# Generated by Django 2.2.13 on 2021-03-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_auto_20201216_1314'),
        ('kiosk', '0030_auto_20210221_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltechnician',
            name='primary_clinic_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinics.ClinicLocation', verbose_name='Primary Clinic Location'),
        ),
        migrations.AddField(
            model_name='technician',
            name='primary_clinic_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinics.ClinicLocation', verbose_name='Primary Clinic Location'),
        ),
    ]
