# Generated by Django 2.2.19 on 2021-04-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0031_auto_20210311_0047'),
        ('kiosk', '0031_action_assessment'),
    ]

    operations = [
    ]
