# Generated by Django 2.2.19 on 2021-04-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk', '0032_merge_20210420_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='fhir_id',
            field=models.CharField(max_length=256, verbose_name="FHIR ID", null=True, blank=True),
        ),
        migrations.AddField(
            model_name='historicalassessment',
            name='fhir_id',
            field=models.CharField(max_length=256, verbose_name="FHIR ID", null=True, blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='fhir_id',
            field=models.CharField(max_length=256, verbose_name="FHIR ID", null=True, blank=True),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='fhir_id',
            field=models.CharField(max_length=256, verbose_name="FHIR ID", null=True, blank=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='fhir_id',
            field=models.CharField(max_length=256, verbose_name="FHIR ID", null=True, blank=True),
        ),
    ]
