# Generated by Django 2.2.19 on 2021-04-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0033_auto_20210420_1145'),
    ]

    operations = [

    ]
