# Generated by Django 2.2.19 on 2021-04-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_auto_20210422_1249'),
        ('kiosk', '0034_auto_20210420_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltechnician',
            old_name='clinic',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='clinic',
            new_name='system',
        ),
        migrations.AlterField(
            model_name='historicaltechnician',
            name='system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='clinics.HealthcareSystem', verbose_name='Healthcare System'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.HealthcareSystem',
                                    verbose_name='Healthcare System'),
        ),
    ]


"""
    operations = [
        migrations.RemoveField(
            model_name='historicaltechnician',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='clinic',
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinics.HealthcareSystem', verbose_name='Healthcare System'),
        ),
        migrations.AddField(
            model_name='technician',
            name='system',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clinics.HealthcareSystem', verbose_name='Healthcare System'),
            preserve_default=False,
        ),
    ]
"""
