# Generated by Django 2.2.19 on 2021-04-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0035_auto_20210420_1245'),
    ]

    operations = [

    ]
