# Generated by Django 2.2.19 on 2021-04-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0020_auto_20210429_1537'),
        ('kiosk', '0035_auto_20210422_1249'),
    ]

    operations = [
        # RENAME FIELDS
        migrations.RenameField(
            model_name='patient',
            old_name='clinic_location',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='historicalpatient',
            old_name='clinic_location',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='primary_clinic_location',
            new_name='primary_department',
        ),
        migrations.RenameField(
            model_name='historicaltechnician',
            old_name='primary_clinic_location',
            new_name='primary_department',
        ),

        # ALTER FIELD REFERENCES
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='clinics.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='clinics.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='primary_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='clinics.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='historicaltechnician',
            name='primary_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='clinics.Department', verbose_name='Department'),
        ),
    ]
