# Generated by Django 2.2.19 on 2021-05-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0036_auto_20210420_2032'),
        ('kiosk', '0036_auto_20210429_1537'),
    ]

    operations = [
    ]
