# Generated by Django 2.2.24 on 2021-08-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0040_auto_20210610_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='fhir_id',
        ),
        migrations.AlterField(
            model_name='historicaltechnician',
            name='fhir_id',
            field=models.CharField(max_length=256, null=True, verbose_name='FHIR IDs'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='fhir_id',
            field=models.CharField(max_length=256, null=True, verbose_name='FHIR IDs'),
        ),
    ]
