# Generated by Django 2.2.24 on 2021-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0041_auto_20210803_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='FHIR IDs'),
        ),
        migrations.AlterField(
            model_name='historicalencounter',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='FHIR IDs'),
        ),
        migrations.AlterField(
            model_name='historicaltechnician',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='FHIR IDs'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='FHIR IDs'),
        ),
    ]
