# Generated by Django 2.2.24 on 2021-06-10 18:57

from django.db import migrations, transaction


def update_encounter(apps, schema_editor):
    Encounter = apps.get_model('kiosk', 'Encounter')
    Clinic = apps.get_model("clinics", "Clinic")
    Department = apps.get_model("clinics", "Department")
    PatientDepartmentSharing = apps.get_model("kiosk", "PatientDepartmentSharing")

    for encounter in Encounter.objects.all():
        original_id = encounter.department_id
        clinic = Clinic.objects.get(pk=original_id)
        department = Department.objects.filter(clinic=clinic, status="active").first()
        encounter.department = department
        encounter.save()

        PatientDepartmentSharing.objects.filter(patient=encounter.patient, department_id=original_id).update(department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0042_auto_20210803_1530'),
    ]

    operations = [
        migrations.RunPython(update_encounter),
    ]
