# Generated by Django 2.2.24 on 2021-07-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0042_auto_20210803_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='note_type',
            field=models.CharField(choices=[('stability-plan', 'Stability Plan'), ('narrative-note', 'Narrative Note')], default='narrative-note', max_length=31, verbose_name='Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalamendment',
            name='note_type',
            field=models.CharField(choices=[('stability-plan', 'Stability Plan'), ('narrative-note', 'Narrative Note')], default='narrative-note', max_length=31, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
