# Generated by Django 2.2.24 on 2021-08-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0043_update_dept_ids_in_encounter'),
        ('kiosk', '0055_auto_20210719_1612'),
    ]

    operations = [
    ]
