# Generated by Django 2.2.24 on 2021-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0057_auto_20210814_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentlocks',
            name='acknowledged',
            field=models.BooleanField(default=False, help_text='Indicates whether the patient has acknowledge the assessment lock change'),
        ),
    ]
