# Generated by Django 2.2.24 on 2021-08-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0059_auto_20210817_1918'),
        ('kiosk', '0059_auto_20210826_1901'),
    ]

    operations = [
    ]
