# Generated by Django 2.2.24 on 2021-09-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0061_add_status_to_patient_session'),
    ]

    operations = [
    ]
