# Generated by Django 2.2.26 on 2022-01-11 00:08

from django.db import migrations, models
import django.utils.timezone

def populated_assignment_locks_activity(apps, schema_editor):
    AssignmentLocks = apps.get_model("kiosk", "AssignmentLocks")
    for record in AssignmentLocks.objects.all():
        patient_session = record.patient_session
        if hasattr(patient_session, "srat"):
            record.activity = patient_session.srat.assignedactivity
            record.save()
        else:
            record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0065_auto_20220110_1608'),
    ]

    operations = [
        migrations.RunPython(
            populated_assignment_locks_activity
        ),
    ]
