# Generated by Django 2.2.24 on 2022-02-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0067_auto_20220110_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentlocks',
            options={'ordering': ('-modified',), 'verbose_name': 'Assessment Lock', 'verbose_name_plural': 'Assessment Locks'},
        ),
    ]
