# Generated by Django 2.2.24 on 2022-02-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0068_auto_20220203_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmeasurements',
            name='screen',
            field=models.CharField(blank=True, help_text='Screen where the measurement occurred', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientmeasurements',
            name='ux_format',
            field=models.CharField(blank=True, help_text='UX Format of the measurement', max_length=50, null=True),
        ),
    ]
