# Generated by Django 3.1.14 on 2022-02-18 18:02

from django.db import migrations
import jaspr.apps.common.fields.encrypted_json_field


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0070_auto_20220216_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisstabilityplan',
            name='supportive_people',
            field=jaspr.apps.common.fields.encrypted_json_field.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrisisstabilityplan',
            name='supportive_people',
            field=jaspr.apps.common.fields.encrypted_json_field.EncryptedJSONField(blank=True, null=True),
        ),
    ]
