# Generated by Django 3.1.14 on 2022-02-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0071_auto_20220218_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentlocks',
            options={'ordering': ['-modified'], 'verbose_name': 'Assessment Lock', 'verbose_name_plural': 'Assessment Locks'},
        ),
        migrations.AlterModelOptions(
            name='copingstrategy',
            options={'ordering': ['title'], 'verbose_name': 'Coping Strategy', 'verbose_name_plural': 'Coping Strategies'},
        ),
        migrations.AlterModelOptions(
            name='copingstrategycategory',
            options={'ordering': ['name'], 'verbose_name': 'Coping Strategy Category', 'verbose_name_plural': 'Coping Strategy Categories'},
        ),
        migrations.AlterModelOptions(
            name='guidemessage',
            options={'ordering': ['name'], 'verbose_name': 'Guide Message', 'verbose_name_plural': 'Guide Messages'},
        ),
        migrations.AlterModelOptions(
            name='patientcopingstrategy',
            options={'ordering': ['title'], 'verbose_name': 'Patient Coping Strategy', 'verbose_name_plural': 'Patient Coping Strategies'},
        ),
    ]
