# Generated by Django 3.2.12 on 2022-03-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0069_auto_20220207_1615'),
        ('kiosk', '0072_auto_20220218_1205'),
    ]

    operations = [
    ]
