# Generated by Django 3.2.12 on 2022-03-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0073_merge_0069_auto_20220207_1615_0072_auto_20220218_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentlocks',
            options={'ordering': ['-modified'], 'verbose_name': 'Assessment Lock', 'verbose_name_plural': 'Assessment Locks'},
        ),
    ]
