# Generated by Django 3.2.12 on 2022-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0074_alter_assignmentlocks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasprsession',
            name='technician_operated',
            field=models.BooleanField(default=False, verbose_name='Technician operating on behalf of patient?'),
            preserve_default=False,
        ),
    ]
