# Generated by Django 3.2.12 on 2022-04-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0075_jasprsession_technician_operated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedactivity',
            options={'verbose_name_plural': 'Assigned Activities'},
        ),
    ]
