# Generated by Django 3.2.12 on 2022-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0076_alter_assignedactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltechnician',
            name='coach_modeling_complete',
            field=models.BooleanField(default=False, help_text='Has this technician been provided with "At Elbow" support by a Jaspr Coach?', verbose_name='Jaspr Coach Modeling'),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='practice_with_support_complete',
            field=models.BooleanField(default=False, help_text='Has the technician shared positive feedback', verbose_name='Practice with Support'),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='training_complete',
            field=models.BooleanField(default=False, help_text='Has the technician completed their Jaspr education and training?', verbose_name='Education/Training Completed'),
        ),
        migrations.AddField(
            model_name='technician',
            name='coach_modeling_complete',
            field=models.BooleanField(default=False, help_text='Has this technician been provided with "At Elbow" support by a Jaspr Coach?', verbose_name='Jaspr Coach Modeling'),
        ),
        migrations.AddField(
            model_name='technician',
            name='practice_with_support_complete',
            field=models.BooleanField(default=False, help_text='Has the technician shared positive feedback', verbose_name='Practice with Support'),
        ),
        migrations.AddField(
            model_name='technician',
            name='training_complete',
            field=models.BooleanField(default=False, help_text='Has the technician completed their Jaspr education and training?', verbose_name='Education/Training Completed'),
        ),
    ]
