# Generated by Django 3.2.12 on 2022-04-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0077_auto_20220406_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='technician_operated',
            field=models.BooleanField(default=False, help_text='Indicates that the provider assisted the patient directly in answering questions', verbose_name='Technician Operated'),
        ),
        migrations.AddField(
            model_name='historicalencounter',
            name='technician_operated',
            field=models.BooleanField(default=False, help_text='Indicates that the provider assisted the patient directly in answering questions', verbose_name='Technician Operated'),
        ),
    ]
