# Generated by Django 2.2.24 on 2021-06-10 21:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import jaspr.apps.common.fields.encrypted_array_field
import jaspr.apps.common.fields.encrypted_boolean_field
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0037_merge_20210506_1156'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JAHAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=100, no_check_for_status=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'JAH Account',
                'verbose_name_plural': 'JAH Accounts',
            },
        ),
        migrations.CreateModel(
            name='PatientCopingStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=100, no_check_for_status=True)),
                ('title', models.CharField(help_text='Public title of this coping strategy, currently used to connect frontend to backend as a key.', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jah_patientcopingstrategy_coping_strategy_category', to='kiosk.CopingStrategyCategory')),
                ('jah_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jah.JAHAccount', verbose_name='JAH Account')),
            ],
            options={
                'verbose_name': 'Patient Coping Strategy',
                'verbose_name_plural': 'Patient Coping Strategies',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPatientCopingStrategy',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('choice1', 'choice1'), ('choice2', 'choice2')], default='choice1', max_length=100, no_check_for_status=True)),
                ('title', models.CharField(help_text='Public title of this coping strategy, currently used to connect frontend to backend as a key.', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kiosk.CopingStrategyCategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jah_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jah.JAHAccount', verbose_name='JAH Account')),
            ],
            options={
                'verbose_name': 'historical Patient Coping Strategy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJAHAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('choice1', 'choice1'), ('choice2', 'choice2')], default='choice1', max_length=100, no_check_for_status=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kiosk.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'historical JAH Account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCrisisStabilityPlan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('choice1', 'choice1'), ('choice2', 'choice2')], default='choice1', max_length=100, no_check_for_status=True)),
                ('reasons_live', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=5)),
                ('strategies_general', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_firearm', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_medicine', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_places', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_other', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_custom', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('means_support_yes_no', jaspr.apps.common.fields.encrypted_boolean_field.EncryptedBooleanField(null=True)),
                ('means_support_who', fernet_fields.fields.EncryptedCharField(blank=True, max_length=10000, null=True)),
                ('coping_body', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_distract', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_help_others', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_courage', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_senses', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('supportive_people', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None)),
                ('coping_top', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_stressors', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_thoughts', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_feelings', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_actions', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_top', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jah_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jah.JAHAccount', verbose_name='JAH Account')),
            ],
            options={
                'verbose_name': 'historical JAH Crisis Stability Plan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CrisisStabilityPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=100, no_check_for_status=True)),
                ('reasons_live', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=5)),
                ('strategies_general', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_firearm', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_medicine', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_places', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_other', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('strategies_custom', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('means_support_yes_no', jaspr.apps.common.fields.encrypted_boolean_field.EncryptedBooleanField(null=True)),
                ('means_support_who', fernet_fields.fields.EncryptedCharField(blank=True, max_length=10000, null=True)),
                ('coping_body', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_distract', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_help_others', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_courage', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('coping_senses', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('supportive_people', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None)),
                ('coping_top', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_stressors', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_thoughts', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_feelings', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_actions', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('ws_top', jaspr.apps.common.fields.encrypted_array_field.EncryptedArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None)),
                ('jah_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jah.JAHAccount', verbose_name='JAH Account')),
            ],
            options={
                'verbose_name': 'JAH Crisis Stability Plan',
                'verbose_name_plural': 'JAH Crisis Stability Plans',
            },
        ),
        migrations.AddConstraint(
            model_name='patientcopingstrategy',
            constraint=models.UniqueConstraint(fields=('title', 'jah_account'), name='patientcopingstrategy_title_and_patient_jah_account_unique_together'),
        ),
    ]
