# Generated by Django 2.2.13 on 2020-06-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kiosk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcliniclocationtechnician",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="kiosk.Technician",
            ),
        ),
        migrations.AddField(
            model_name="historicalcliniclocation",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.Clinic",
            ),
        ),
        migrations.AddField(
            model_name="historicalcliniclocation",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalclinic",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cliniclocationtechnician",
            name="clinic_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clinics.ClinicLocation"
            ),
        ),
        migrations.AddField(
            model_name="cliniclocationtechnician",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kiosk.Technician"
            ),
        ),
        migrations.AddField(
            model_name="cliniclocation",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clinics.Clinic"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cliniclocationtechnician",
            unique_together={("technician", "clinic_location")},
        ),
    ]
