# Generated by Django 2.2.13 on 2020-07-31 22:50

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_auto_20200619_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="activation_code",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True, max_length=63, verbose_name="Activation Code"
            ),
        ),
        migrations.AddField(
            model_name="historicalclinic",
            name="activation_code",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True, max_length=63, verbose_name="Activation Code"
            ),
        ),
        migrations.AlterField(
            model_name="cliniclocation",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clinics.Clinic",
                verbose_name="Clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcliniclocation",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.Clinic",
                verbose_name="Clinic",
            ),
        ),
    ]
