# Generated by Django 2.2.13 on 2020-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_auto_20200731_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="organization_code",
            field=models.SlugField(
                blank=True,
                help_text="Code used in subdomain of clinic portal.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclinic",
            name="organization_code",
            field=models.SlugField(
                blank=True,
                help_text="Code used in subdomain of clinic portal.",
                null=True,
            ),
        ),
    ]
