# Generated by Django 2.2.13 on 2020-10-07 16:33

import django_better_admin_arrayfield.models.fields
import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0008_auto_20200914_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliniclocation",
            name="ip_address_ranges_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.CidrAddressField(
                    max_length=43, verbose_name="IP Address Range (CIDR)"
                ),
                blank=True,
                default=list,
                help_text="If you have IP (v4 or v6) address ranges as CIDR blocks, you can add them here.",
                size=None,
                verbose_name="IP Address Ranges Whitelist (CIDR)",
            ),
        ),
        migrations.AddField(
            model_name="cliniclocation",
            name="ip_addresses_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.InetAddressField(
                    max_length=39, verbose_name="IP Address"
                ),
                blank=True,
                default=list,
                help_text="If you have individual IP Addresses (v4 or v6) to whitelist, you can add them here.",
                size=None,
                verbose_name="IP Addresses Whitelist",
            ),
        ),
        migrations.AddField(
            model_name="historicalcliniclocation",
            name="ip_address_ranges_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.CidrAddressField(
                    max_length=43, verbose_name="IP Address Range (CIDR)"
                ),
                blank=True,
                default=list,
                help_text="If you have IP (v4 or v6) address ranges as CIDR blocks, you can add them here.",
                size=None,
                verbose_name="IP Address Ranges Whitelist (CIDR)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcliniclocation",
            name="ip_addresses_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.InetAddressField(
                    max_length=39, verbose_name="IP Address"
                ),
                blank=True,
                default=list,
                help_text="If you have individual IP Addresses (v4 or v6) to whitelist, you can add them here.",
                size=None,
                verbose_name="IP Addresses Whitelist",
            ),
        ),
    ]
