# Generated by Django 2.2.13 on 2020-10-13 19:10

import django_better_admin_arrayfield.models.fields
import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0009_auto_20201007_0933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliniclocation",
            name="ip_address_ranges_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.CidrAddressField(
                    max_length=43, verbose_name="IP Address Range (CIDR)"
                ),
                blank=True,
                default=list,
                help_text="If you have IP (v4 or v6) address ranges as CIDR blocks, you can add them here. At the time of writing, Jaspr only has IPv4 addresses though, so while you are welcome to add IPv6 addresses for the future, make sure to add at least one IPv4 address range for the time being (if you are going to add an IP address range in the first place).",
                size=None,
                verbose_name="IP Address Ranges Whitelist (CIDR)",
            ),
        ),
        migrations.AlterField(
            model_name="cliniclocation",
            name="ip_addresses_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.InetAddressField(
                    max_length=39, verbose_name="IP Address"
                ),
                blank=True,
                default=list,
                help_text="If you have individual IP Addresses (v4 or v6) to whitelist, you can add them here. At the time of writing, Jaspr only has IPv4 addresses though, so while you are welcome to add IPv6 addresses for the future, make sure to add at least one IPv4 address for the time being (if you are going to add an IP address in the first place).",
                size=None,
                verbose_name="IP Addresses Whitelist",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcliniclocation",
            name="ip_address_ranges_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.CidrAddressField(
                    max_length=43, verbose_name="IP Address Range (CIDR)"
                ),
                blank=True,
                default=list,
                help_text="If you have IP (v4 or v6) address ranges as CIDR blocks, you can add them here. At the time of writing, Jaspr only has IPv4 addresses though, so while you are welcome to add IPv6 addresses for the future, make sure to add at least one IPv4 address range for the time being (if you are going to add an IP address range in the first place).",
                size=None,
                verbose_name="IP Address Ranges Whitelist (CIDR)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcliniclocation",
            name="ip_addresses_whitelist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=netfields.fields.InetAddressField(
                    max_length=39, verbose_name="IP Address"
                ),
                blank=True,
                default=list,
                help_text="If you have individual IP Addresses (v4 or v6) to whitelist, you can add them here. At the time of writing, Jaspr only has IPv4 addresses though, so while you are welcome to add IPv6 addresses for the future, make sure to add at least one IPv4 address for the time being (if you are going to add an IP address in the first place).",
                size=None,
                verbose_name="IP Addresses Whitelist",
            ),
        ),
    ]
