# Generated by Django 2.2.19 on 2021-04-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0033_auto_20210420_1145'),
        ('clinics', '0011_auto_20201216_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclocationtechnician',
            name='fhir_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.Technician', verbose_name='FHIR_IDs'),
        ),
        migrations.AddField(
            model_name='historicalcliniclocationtechnician',
            name='fhir_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kiosk.Technician', verbose_name='FHIR_IDs'),
        ),
    ]
