# Generated by Django 2.2.19 on 2021-04-22 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0034_auto_20210420_1237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0013_auto_20210420_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clinic',
            new_name='HealthcareSystem',
        ),
        migrations.RenameModel(
            old_name='HistoricalClinic',
            new_name='HistoricalHealthcareSystem',
        ),
        migrations.RenameField(
            model_name='cliniclocation',
            old_name='clinic',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='historicalcliniclocation',
            old_name='clinic',
            new_name='system',
        ),
    ]
