# Generated by Django 2.2.19 on 2021-04-29 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk', '0035_auto_20210422_1249'),
        ('clinics', '0019_auto_20210422_1249'),
    ]

    operations = [
        # CLINIC
        migrations.RenameModel(
            old_name='ClinicLocation',
            new_name='Clinic',
        ),
        migrations.RenameModel(
            old_name='HistoricalClinicLocation',
            new_name='HistoricalClinic',
        ),

        # DEPARTMENT
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('status', model_utils.fields.StatusField(
                    choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived')],
                    default='active', max_length=100, no_check_for_status=True)),
                ('name', models.CharField(max_length=125, verbose_name='Name')),
                ('clinic', models.ForeignKey('Clinic', on_delete=models.PROTECT, null=True, blank=True))
            ],
            options={
                'abstract': False,
            },
        ),

        # DEPARTMENT TECHNICIAN
        migrations.RenameModel(
            old_name='ClinicLocationTechnician',
            new_name='DepartmentTechnician',
        ),
        migrations.RenameModel(
            old_name='HistoricalClinicLocationTechnician',
            new_name='HistoricalDepartmentTechnician',
        ),
        migrations.RenameField(
            model_name='departmenttechnician',
            old_name='clinic_location',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='historicaldepartmenttechnician',
            old_name='clinic_location',
            new_name='department',
        ),

        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Clinic', 'verbose_name_plural': 'Clinics'},
        ),
        migrations.AlterModelOptions(
            name='historicalclinic',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Clinic'},
        ),
    ]
