# Generated by Django 2.2.24 on 2021-06-10 18:57

from django.db import migrations


def create_departments(apps, schema_editor):
    Clinic = apps.get_model('clinics', 'Clinic')
    Department = apps.get_model('clinics', 'Department')

    for clinic in Clinic.objects.all():

        dept = Department.objects.create(
            clinic=clinic,
            name="Default",
        )
        dept.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0020_auto_20210429_1537'),
    ]

    operations = [
        migrations.RunPython(create_departments),
    ]
