# Generated by Django 2.2.19 on 2021-05-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0021_custom_create_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttechnician',
            options={'verbose_name': 'Department Technician', 'verbose_name_plural': 'Department Technician Records'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartmenttechnician',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Department Technician'},
        ),
        migrations.AlterField(
            model_name='department',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.Clinic', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='departmenttechnician',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.Department', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='historicaldepartmenttechnician',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinics.Department'),
        ),
    ]
