# Generated by Django 2.2.24 on 2021-06-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0022_auto_20210506_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcaresystem',
            options={'verbose_name': 'Healthcare System', 'verbose_name_plural': 'Healthcare Systems'},
        ),
        migrations.AlterModelOptions(
            name='historicalhealthcaresystem',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Healthcare System'},
        ),
    ]
