# Generated by Django 2.2.24 on 2021-06-10 18:57

from django.db import migrations, transaction


def update_department_technicians(apps, schema_editor):
    Clinic = apps.get_model('clinics', 'Clinic')
    Department = apps.get_model('clinics', 'Department')
    DepartmentTechnician = apps.get_model('clinics', 'DepartmentTechnician')

    with transaction.atomic():
        defer_list = []

        # Deleta all DT's but same the proper relationships in a list
        for tech in DepartmentTechnician.objects.filter().all():
            clinic = Clinic.objects.get(pk=tech.department_id)
            department = Department.objects.filter(clinic=clinic, status="active").first()
            defer_list.append(
                (tech.technician.pk, department.pk, tech.status)
            )
            tech.delete()

        for pair in defer_list:
            DepartmentTechnician.objects.create(
                technician_id=pair[0],
                department_id=pair[1],
                status=pair[2]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0024_add_question_lists_to_departments'),
    ]

    operations = [
        migrations.RunPython(update_department_technicians),
    ]
