# Generated by Django 2.2.24 on 2021-08-27 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0027_auto_20210814_2319'),
    ]

    operations = [

    ]
