# Generated by Django 2.2.24 on 2021-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0028_auto_20210826_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tablet_department_code',
            field=models.CharField(blank=True, help_text='Tablet department codes encoded in the URL must match this code in order for the tablet to authenticate to this department', max_length=32, null=True, unique=True, verbose_name='Tablet Department Code'),
        ),
    ]
