# Generated by Django 2.2.24 on 2021-10-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0029_department_tablet_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.HealthcareSystem', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='historicalclinic',
            name='system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinics.HealthcareSystem', verbose_name='System'),
        ),
    ]
