# Generated by Django 2.2.24 on 2021-12-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0030_auto_20211019_0933'),
    ]

    operations = [

    ]
