# Generated by Django 2.2.24 on 2021-12-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0031_auto_20211220_1709'),
    ]

    operations = [

    ]
