# Generated by Django 2.2.26 on 2022-01-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0032_auto_20211221_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcaresystem',
            name='tablet_system_code',
            field=models.CharField(blank=True, help_text='Tablet system codes encoded in the URL must match this code in order for the tablet to authenticate to this system', max_length=32, null=True, unique=True, verbose_name='Tablet System Code'),
        ),
        migrations.AddField(
            model_name='historicalhealthcaresystem',
            name='tablet_system_code',
            field=models.CharField(blank=True, db_index=True, help_text='Tablet system codes encoded in the URL must match this code in order for the tablet to authenticate to this system', max_length=32, null=True, verbose_name='Tablet System Code'),
        ),
    ]
