# Generated by Django 3.2.12 on 2022-03-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0034_auto_20220208_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='consent_language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='consent_language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
