# Generated by Django 3.2.12 on 2022-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0036_auto_20220310_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='stability_plan_label',
            field=models.CharField(default='Stability Plan', help_text='Customize the label for stability plans. Common options are "Stability Plan" or "Safety Plan"', max_length=30),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stability_plan_label',
            field=models.CharField(default='Stability Plan', help_text='Customize the label for stability plans. Common options are "Stability Plan" or "Safety Plan"', max_length=30),
        ),
    ]
