version: "3"

services:
  api-server:
    build:
      context: ../../backend/
      dockerfile: ../ops/docker/api-server/Dockerfile
    platform: linux/amd64
    image: ${API_DOCKER_TAG}
    depends_on:
      - redis
      - mailhog
      - postgres
    env_file:
      - ./envs/postgres.env
      - ./envs/redis.env
      - ./envs/app.env
    ports:
      - "5000:5000"

  postgres:
    image: postgres:11.8-alpine
    env_file:
      - ./envs/postgres.env
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8039:8025"

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  rqworker:
    build:
      context: ../../backend/
      dockerfile: ../ops/docker/worker/Dockerfile
    image: ${WORKER_DOCKER_TAG}
    platform: linux/amd64
    depends_on:
      - redis
      - mailhog
    env_file:
      - ./envs/postgres.env
      - ./envs/redis.env
      - ./envs/app.env
    ports: []

  rqscheduler:
    build:
      context: ../../backend/
      dockerfile: ../ops/docker/scheduler/Dockerfile
    image: ${SCHEDULER_DOCKER_TAG}
    platform: linux/amd64
    depends_on:
      - redis
      - mailhog
    env_file:
      - ./envs/postgres.env
      - ./envs/redis.env
      - ./envs/app.env
    ports: []
